name: Update thokomo Playlist

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Public Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Checkout Private Repo Script (future use)
      uses: actions/checkout@v4
      with:
        repository: bpktv/scripting
        token: ${{ secrets.PRIVATE_REPO_TOKEN }}
        path: private-code

    - name: Install dependencies
      run: pip install requests

    - name: Run script
      run: |
        if [ -f private-code/ghop.py ]; then
          python private-code/ghop.py
        else
          python ghop.py
        fi

    - name: Commit Public Repo Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git add playlist.m3u token.json

        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Automated Playlist + Token Update"
          git push
        fi
